baseUrl: /
languageCode: en-us
theme: hello-friend
copyright: ''
paginate: 5

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # "dark" or "light"
  defaultTheme: dark
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 4
  # Enable to show reading time in minutes for posts
  showReadingTime: true

languages:
  en:
    title: PRKD Media
    subtitle: Fun, Free, First Available
    keywords: ''
    menuMore: More
    writtenBy: Written by
    readMore: Read more
    readOtherPosts: Read other posts
    newerPosts: Newer posts
    olderPosts: Older posts
    dateFormatSingle: 2006-01-02
    dateFormatList: 2006-01-02

    params:
      logo:
        logoText: PRKD Media
        logoHomeLink: /


    menu:
      main:
      - identifier: about
        name: About
        url: /about
      - identifier: projects
        name: Projects
        url: /projects
      - identifier: contact
        name: Contact
        url: /contact
