-- Take a JSON object as input generated by the scoring python package
local input_object = {{'Jade Brady', {0, 1, -1, 1, 0, 1, 0, 1, 0}, -13, 'T5'}, {'Sarah Lee', {0, 0, 0, 0, 0, 0, 0, 0, 0}, -11, 'T1'}, {'Daniel Adamec', {-1, -1, -1 , -1, 1, 1, 1, 1, 1}, 9, 'T3'}, {"Austin D'Alessandro", {-1, -1, 1, 1, 0, 0, 1, 1, 1}, -4, "1"}}

local parObject = {}
parObject[-3] = {'Albatross', {0.72,0.45,0.11}}
parObject[-2] = {'Eagle', {0.15,0.37,0.73}}
parObject[-1] = {'Birdie', {0.02,0.6,0.36}}
parObject[0] = {'Par', {0.42,0.41,0.42}}
parObject[1] = {'Bogey', {0.73,0,0.02}}
parObject[2] = {'Double Bogey', {0.57,0.1,0.72}}
parObject[3] = {'Triple Bogey', {0.51,0.38,0.32}}

function UpdateScorecards(object)
    -- Iterate through the entire JSON object and update all of the hole scores for each player at a time
    for i = 1, 4, 1 do
        -- Get the player name and the player identifier
        local playerID = 'Player' .. tostring(i)
        local playerName = object[i][2]
        -- Update the player name
        UpdatePlayerName(playerID .. '_Name', playerName )
        -- Pass the starting score and the scores object
        UpdateFinalScore(playerID, object[i][4])
        -- Update Placing
        UpdateFinalPlacing(playerID .. '_Place', object[i][1])
        for j = 1, 9, 1 do
            local playerScore = parObject[object[i][5][j]]
            ChangeHoleBackground(playerID, j, playerScore)
        end
    end
end

-- Takes the player and hole completed and their score for the hole as input
-- Changes the background colour of the hole for teh given player
function ChangeHoleBackground(player, hole, holeScore)
    local backgroundTools = comp:GetToolList(false, "Background")
    for k, bg in ipairs(backgroundTools) do
        if bg.Name == player .. '_' .. tostring(hole) .. 'B_1' then
            -- Set the colour based on the score
            if not holeScore then
                bg:SetInput("TopLeftRed", 0)
                bg:SetInput("TopLeftGreen", 0)
                bg:SetInput("TopLeftBlue", 0)
                bg:SetInput("TopLeftAlpha", 0)
            else
                bg:SetInput("TopLeftRed", holeScore[2][1])
                bg:SetInput("TopLeftGreen", holeScore[2][2])
                bg:SetInput("TopLeftBlue", holeScore[2][3])
                bg:SetInput("TopLeftAlpha", 1)
            end
        end
    end
end

function UpdatePlayerName(text_name, text_content)
    local textObjects = comp:GetToolList(false, "TextPlus")
    for k, txt in ipairs(textObjects) do
        if txt.Name == text_name then
            -- Update the content of the object
            text_content = string.upper(text_content)
            txt.StyledText:SetExpression('Text("' .. text_content .. '")')
        end
    end
end

function UpdateFinalPlacing(text_name, text_content)
    local textObjects = comp:GetToolList(false, "TextPlus")
    for k, txt in ipairs(textObjects) do
        if txt.Name == text_name then
            -- Update the content of the object
            text_content = string.upper(text_content)
            txt.StyledText:SetExpression('Text("' .. text_content .. '")')
        end
    end
end

function UpdateScoreField(text_name, text_content)
    local textObjects = comp:GetToolList(false, "TextPlus")
    for k, txt in ipairs(textObjects) do
        if txt.Name == text_name then
            -- Update the content of the object
            txt.StyledText:SetExpression(text_content)
        end
    end
end

function UpdateFinalScore(player_id, starting_score)
    -- Construct the player score field name
    local fieldName = player_id .. '_Score'
    -- Process the final score to convert 0 to E and 10 to +10
    if starting_score == 0 then
        starting_score = 'Text("E")'
    elseif starting_score > 0 then
        starting_score = 'Text("+' .. tostring(starting_score) .. '")'
    else
        starting_score = 'Text("' .. tostring(starting_score) .. '")'
    end
    UpdateScoreField(fieldName, starting_score)
end

UpdateScorecards(input_object)